### PR TITLE
New patch release of Golang: v1.19.13

### PR DESCRIPTION
**Pull request by rcrozean**
Update EKS Go Patch Version: v1.19.13-14
SPEC FILE STILL NEEDS THE '%changelog' UPDATED
PLEASE UPDATE WITH THE FOLLOWING FORMAT
```
* Wed Sep 06 2023 Cameron Rozean <rcrozean@amazon.com> - 1.20.8-1
- Bump tracking patch version to 1.20.8 from 1.20.7
```

### CODE REVIEW

**Comment by zafs23** [comment]
looks good to me

**Comment by g-gaston** [comment]
looked at `projects/golang/go/1.19/patches/0008-go-1.19.13-eks-cmd-go-internal-vcs-error-out-.patch` and that lgtm

**Pull request merged**
