### PR TITLE
add go 1.23 image and license image to builder-base Dockerfile

### PR DESCRIPTION
**Pull request by vineeth-bandi**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by srbgupta86** [comment]
Shouldn't we define GOLANG_VERSION_123 in https://github.com/aws/eks-distro-build-tooling/blob/main/builder-base/versions.yaml?

**Comment by vineeth-bandi** [comment]
> Shouldn't we define GOLANG_VERSION_123 in https://github.com/aws/eks-distro-build-tooling/blob/main/builder-base/versions.yaml?

Thats included in the previous PR #1501.

**Pull request merged**
