### PR TITLE
Remove Golang 1.15 and 1.16 versions

### PR DESCRIPTION
**Pull request by zafs23**
*Issue #, if available:*

*Description of changes:*
After EKS-D started supporting K8 1.27, EKS-D has stopped supporting [k8 1.22](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar). All our projects supporting k8 1.23-1.27 are built from  EKS-Go 1.17-1.20. Thus, we are moving forward with deprecating EKS-Go 1.15 and 1.16 (will not update or backport new CVE's). All our Golang artifacts from EKS-Go 1.15 and 1.16 are still will be available in our Public ECR. 

**As this poses immediate risk to users of EKS-Go 1.15 and 1.16, we advise them it is HIGHLY recommended that users of `EKS-GO v1.15 - v1.16` update to a supported version of EKS-Go (v1.17+) as soon as possible.**

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by kschumy** [comment]
Do we need to remove any of the following?
1. https://github.com/aws/eks-distro-build-tooling/blob/bb66807b9090c64e292bce53262afc184509effd/eks-distro-base/tests/run_tests.sh#L658-L680
1. https://github.com/aws/eks-distro-build-tooling/blob/bb66807b9090c64e292bce53262afc184509effd/builder-base/versions.yaml#L6
1. https://github.com/aws/eks-distro-build-tooling/blob/bb66807b9090c64e292bce53262afc184509effd/builder-base/Dockerfile#L211-L225
1. https://github.com/aws/eks-distro-build-tooling/blob/bb66807b9090c64e292bce53262afc184509effd/builder-base/scripts/install_go_licenses.sh#L35C1-L37
1. Any of the 1.15 and 1.16 files under here? https://github.com/aws/eks-distro-build-tooling/tree/bb66807b9090c64e292bce53262afc184509effd/eks-distro-base-updates

**Comment by zafs23** [comment]
@kschumy we have to keep all the builder-base 1.16 references for the time being

**Review by danbudris — APPROVED** [review]

**Pull request merged**
