### PR TITLE
Set squash as default method for Prow merges

### PR DESCRIPTION
**Pull request by bnrjee**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by vivek-koppuru — CHANGES_REQUESTED** [review]
Can we rename the commit to "Set squash as default method for Prow merges"? Initially when I read this, I thought you were saying this commit was git squashing multi-commit merges or something.

**Comment by jaxesn** [comment]
After this merges, ill update the github settings for our 3 repos to have only `Allow squash merging` checked. The only time that even comes into play is if one us were to manually merge. Thoughts?

Screen Shot 2021-01-20 at 8 54 46 AM

**Comment by bnrjee** [comment]
> Can we rename the commit to "Set squash as default method for Prow merges"? Initially when I read this, I thought you were saying this commit was git squashing multi-commit merges or something.

Done

**Review by vivek-koppuru — APPROVED** [review]
/lgtm

**Pull request merged**
