### PR TITLE
Fix Makefile for humans

### PR DESCRIPTION
**Pull request by TerryHowe**
Fix the Makeflle for humans

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by bnrjee** [comment]
@TerryHowe: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
aws-for-fluent-bit-helm-chart-tooling-presubmit | 331e93de100f92879034d925b35317bb1a39881e | [link](https://prow.mhausler.people.a2z.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-distro-build-tooling/79/aws-for-fluent-bit-helm-chart-tooling-presubmit/1349417968873771008) | `/test aws-for-fluent-bit-helm-chart-tooling-presubmit`

[Full PR test history](https://prow.mhausler.people.a2z.com/pr-history?org=aws&repo=eks-distro-build-tooling&pr=79). [Your PR dashboard](https://prow.mhausler.people.a2z.com/pr?query=is:pr+state:open+author:TerryHowe).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by bnrjee** [comment]
@TerryHowe: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
aws-for-fluent-bit-helm-chart-tooling-presubmit | 331e93de100f92879034d925b35317bb1a39881e | [link](https://prow.mhausler.people.a2z.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-distro-build-tooling/79/aws-for-fluent-bit-helm-chart-tooling-presubmit/1349417968873771008) | `/test aws-for-fluent-bit-helm-chart-tooling-presubmit`
release-tooling-presubmit | 331e93de100f92879034d925b35317bb1a39881e | [link](https://prow.mhausler.people.a2z.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-distro-build-tooling/79/release-tooling-presubmit/1349417971436490752) | `/test release-tooling-presubmit`

[Full PR test history](https://prow.mhausler.people.a2z.com/pr-history?org=aws&repo=eks-distro-build-tooling&pr=79). [Your PR dashboard](https://prow.mhausler.people.a2z.com/pr?query=is:pr+state:open+author:TerryHowe).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by bnrjee** [comment]
@TerryHowe: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
aws-for-fluent-bit-helm-chart-tooling-presubmit | 331e93de100f92879034d925b35317bb1a39881e | [link](https://prow.mhausler.people.a2z.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-distro-build-tooling/79/aws-for-fluent-bit-helm-chart-tooling-presubmit/1349417968873771008) | `/test aws-for-fluent-bit-helm-chart-tooling-presubmit`
release-tooling-presubmit | 331e93de100f92879034d925b35317bb1a39881e | [link](https://prow.mhausler.people.a2z.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-distro-build-tooling/79/release-tooling-presubmit/1349417971436490752) | `/test release-tooling-presubmit`
prometheus-helm-chart-tooling-presubmit | 331e93de100f92879034d925b35317bb1a39881e | [link](https://prow.mhausler.people.a2z.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-distro-build-tooling/79/prometheus-helm-chart-tooling-presubmit/1349417970597629952) | `/test prometheus-helm-chart-tooling-presubmit`

[Full PR test history](https://prow.mhausler.people.a2z.com/pr-history?org=aws&repo=eks-distro-build-tooling&pr=79). [Your PR dashboard](https://prow.mhausler.people.a2z.com/pr?query=is:pr+state:open+author:TerryHowe).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by bnrjee** [comment]
@TerryHowe: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
aws-for-fluent-bit-helm-chart-tooling-presubmit | 331e93de100f92879034d925b35317bb1a39881e | [link](https://prow.mhausler.people.a2z.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-distro-build-tooling/79/aws-for-fluent-bit-helm-chart-tooling-presubmit/1349417968873771008) | `/test aws-for-fluent-bit-helm-chart-tooling-presubmit`
release-tooling-presubmit | 331e93de100f92879034d925b35317bb1a39881e | [link](https://prow.mhausler.people.a2z.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-distro-build-tooling/79/release-tooling-presubmit/1349417971436490752) | `/test release-tooling-presubmit`
prometheus-helm-chart-tooling-presubmit | 331e93de100f92879034d925b35317bb1a39881e | [link](https://prow.mhausler.people.a2z.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-distro-build-tooling/79/prometheus-helm-chart-tooling-presubmit/1349417970597629952) | `/test prometheus-helm-chart-tooling-presubmit`
helm-chart-tooling-presubmit | 331e93de100f92879034d925b35317bb1a39881e | [link](https://prow.mhausler.people.a2z.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-distro-build-tooling/79/helm-chart-tooling-presubmit/1349417968974434304) | `/test helm-chart-tooling-presubmit`

[Full PR test history](https://prow.mhausler.people.a2z.com/pr-history?org=aws&repo=eks-distro-build-tooling&pr=79). [Your PR dashboard](https://prow.mhausler.people.a2z.com/pr?query=is:pr+state:open+author:TerryHowe).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by bnrjee** [comment]
@TerryHowe: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
aws-for-fluent-bit-helm-chart-tooling-presubmit | 331e93de100f92879034d925b35317bb1a39881e | [link](https://prow.mhausler.people.a2z.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-distro-build-tooling/79/aws-for-fluent-bit-helm-chart-tooling-presubmit/1349417968873771008) | `/test aws-for-fluent-bit-helm-chart-tooling-presubmit`
release-tooling-presubmit | 331e93de100f92879034d925b35317bb1a39881e | [link](https://prow.mhausler.people.a2z.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-distro-build-tooling/79/release-tooling-presubmit/1349417971436490752) | `/test release-tooling-presubmit`
prometheus-helm-chart-tooling-presubmit | 331e93de100f92879034d925b35317bb1a39881e | [link](https://prow.mhausler.people.a2z.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-distro-build-tooling/79/prometheus-helm-chart-tooling-presubmit/1349417970597629952) | `/test prometheus-helm-chart-tooling-presubmit`
helm-chart-tooling-presubmit | 331e93de100f92879034d925b35317bb1a39881e | [link](https://prow.mhausler.people.a2z.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-distro-build-tooling/79/helm-chart-tooling-presubmit/1349417968974434304) | `/test helm-chart-tooling-presubmit`
athens-tooling-presubmit | 331e93de100f92879034d925b35317bb1a39881e | [link](https://prow.mhausler.people.a2z.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-distro-build-tooling/79/athens-tooling-presubmit/1349417968836022272) | `/test athens-tooling-presubmit`

[Full PR test history](https://prow.mhausler.people.a2z.com/pr-history?org=aws&repo=eks-distro-build-tooling&pr=79). [Your PR dashboard](https://prow.mhausler.people.a2z.com/pr?query=is:pr+state:open+author:TerryHowe).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by bnrjee** [comment]
@TerryHowe: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
aws-for-fluent-bit-helm-chart-tooling-presubmit | 331e93de100f92879034d925b35317bb1a39881e | [link](https://prow.mhausler.people.a2z.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-distro-build-tooling/79/aws-for-fluent-bit-helm-chart-tooling-presubmit/1349417968873771008) | `/test aws-for-fluent-bit-helm-chart-tooling-presubmit`
release-tooling-presubmit | 331e93de100f92879034d925b35317bb1a39881e | [link](https://prow.mhausler.people.a2z.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-distro-build-tooling/79/release-tooling-presubmit/1349417971436490752) | `/test release-tooling-presubmit`
prometheus-helm-chart-tooling-presubmit | 331e93de100f92879034d925b35317bb1a39881e | [link](https://prow.mhausler.people.a2z.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-distro-build-tooling/79/prometheus-helm-chart-tooling-presubmit/1349417970597629952) | `/test prometheus-helm-chart-tooling-presubmit`
helm-chart-tooling-presubmit | 331e93de100f92879034d925b35317bb1a39881e | [link](https://prow.mhausler.people.a2z.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-distro-build-tooling/79/helm-chart-tooling-presubmit/1349417968974434304) | `/test helm-chart-tooling-presubmit`
athens-tooling-presubmit | 331e93de100f92879034d925b35317bb1a39881e | [link](https://prow.mhausler.people.a2z.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-distro-build-tooling/79/athens-tooling-presubmit/1349417968836022272) | `/test athens-tooling-presubmit`
amazon-eks-pod-identity-webhook-tooling-presubmit | 331e93de100f92879034d925b35317bb1a39881e | [link](https://prow.mhausler.people.a2z.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-distro-build-tooling/79/amazon-eks-pod-identity-webhook-tooling-presubmit/1349417968789884928) | `/test amazon-eks-pod-identity-webhook-tooling-presubmit`

[Full PR test history](https://prow.mhausler.people.a2z.com/pr-history?org=aws&repo=eks-distro-build-tooling&pr=79). [Your PR dashboard](https://prow.mhausler.people.a2z.com/pr?query=is:pr+state:open+author:TerryHowe).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by bnrjee** [comment]
@TerryHowe: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
aws-for-fluent-bit-helm-chart-tooling-presubmit | 331e93de100f92879034d925b35317bb1a39881e | [link](https://prow.mhausler.people.a2z.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-distro-build-tooling/79/aws-for-fluent-bit-helm-chart-tooling-presubmit/1349417968873771008) | `/test aws-for-fluent-bit-helm-chart-tooling-presubmit`
release-tooling-presubmit | 331e93de100f92879034d925b35317bb1a39881e | [link](https://prow.mhausler.people.a2z.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-distro-build-tooling/79/release-tooling-presubmit/1349417971436490752) | `/test release-tooling-presubmit`
prometheus-helm-chart-tooling-presubmit | 331e93de100f92879034d925b35317bb1a39881e | [link](https://prow.mhausler.people.a2z.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-distro-build-tooling/79/prometheus-helm-chart-tooling-presubmit/1349417970597629952) | `/test prometheus-helm-chart-tooling-presubmit`
helm-chart-tooling-presubmit | 331e93de100f92879034d925b35317bb1a39881e | [link](https://prow.mhausler.people.a2z.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-distro-build-tooling/79/helm-chart-tooling-presubmit/1349417968974434304) | `/test helm-chart-tooling-presubmit`
athens-tooling-presubmit | 331e93de100f92879034d925b35317bb1a39881e | [link](https://prow.mhausler.people.a2z.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-distro-build-tooling/79/athens-tooling-presubmit/1349417968836022272) | `/test athens-tooling-presubmit`
amazon-eks-pod-identity-webhook-tooling-presubmit | 331e93de100f92879034d925b35317bb1a39881e | [link](https://prow.mhausler.people.a2z.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-distro-build-tooling/79/amazon-eks-pod-identity-webhook-tooling-presubmit/1349417968789884928) | `/test amazon-eks-pod-identity-webhook-tooling-presubmit`
eks-distro-base-tooling-presubmit | 331e93de100f92879034d925b35317bb1a39881e | [link](https://prow.mhausler.people.a2z.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-distro-build-tooling/79/eks-distro-base-tooling-presubmit/1349417968928296960) | `/test eks-distro-base-tooling-presubmit`

[Full PR test history](https://prow.mhausler.people.a2z.com/pr-history?org=aws&repo=eks-distro-build-tooling&pr=79). [Your PR dashboard](https://prow.mhausler.people.a2z.com/pr?query=is:pr+state:open+author:TerryHowe).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by bnrjee** [comment]
@TerryHowe: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
aws-for-fluent-bit-helm-chart-tooling-presubmit | 331e93de100f92879034d925b35317bb1a39881e | [link](https://prow.mhausler.people.a2z.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-distro-build-tooling/79/aws-for-fluent-bit-helm-chart-tooling-presubmit/1349417968873771008) | `/test aws-for-fluent-bit-helm-chart-tooling-presubmit`
release-tooling-presubmit | 331e93de100f92879034d925b35317bb1a39881e | [link](https://prow.mhausler.people.a2z.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-distro-build-tooling/79/release-tooling-presubmit/1349417971436490752) | `/test release-tooling-presubmit`
prometheus-helm-chart-tooling-presubmit | 331e93de100f92879034d925b35317bb1a39881e | [link](https://prow.mhausler.people.a2z.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-distro-build-tooling/79/prometheus-helm-chart-tooling-presubmit/1349417970597629952) | `/test prometheus-helm-chart-tooling-presubmit`
helm-chart-tooling-presubmit | 331e93de100f92879034d925b35317bb1a39881e | [link](https://prow.mhausler.people.a2z.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-distro-build-tooling/79/helm-chart-tooling-presubmit/1349417968974434304) | `/test helm-chart-tooling-presubmit`
athens-tooling-presubmit | 331e93de100f92879034d925b35317bb1a39881e | [link](https://prow.mhausler.people.a2z.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-distro-build-tooling/79/athens-tooling-presubmit/1349417968836022272) | `/test athens-tooling-presubmit`
amazon-eks-pod-identity-webhook-tooling-presubmit | 331e93de100f92879034d925b35317bb1a39881e | [link](https://prow.mhausler.people.a2z.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-distro-build-tooling/79/amazon-eks-pod-identity-webhook-tooling-presubmit/1349417968789884928) | `/test amazon-eks-pod-identity-webhook-tooling-presubmit`
eks-distro-base-tooling-presubmit | 331e93de100f92879034d925b35317bb1a39881e | [link](https://prow.mhausler.people.a2z.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-distro-build-tooling/79/eks-distro-base-tooling-presubmit/1349417968928296960) | `/test eks-distro-base-tooling-presubmit`
prometheus-alertmanager-tooling-presubmit | 331e93de100f92879034d925b35317bb1a39881e | [link](https://prow.mhausler.people.a2z.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-distro-build-tooling/79/prometheus-alertmanager-tooling-presubmit/1349417969762963456) | `/test prometheus-alertmanager-tooling-presubmit`

[Full PR test history](https://prow.mhausler.people.a2z.com/pr-history?org=aws&repo=eks-distro-build-tooling&pr=79). [Your PR dashboard](https://prow.mhausler.people.a2z.com/pr?query=is:pr+state:open+author:TerryHowe).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Review by jaxesn — APPROVED** [review]
/lgtm

**Pull request merged**
