### PR TITLE
Added go 1.20

### PR DESCRIPTION
**Pull request by kschumy**
*Issue #, if available:*

*Description of changes:*
/hold

----

###  For future reference, this is what I changed from the original spec

````diff
➜ git diff
diff --git a/projects/golang/go/1.20/rpmbuild/SPECS/golang.spec b/projects/golang/go/1.20/rpmbuild/SPECS/golang.spec
index b7a27f4..72fc1c9 100644
--- a/projects/golang/go/1.20/rpmbuild/SPECS/golang.spec
+++ b/projects/golang/go/1.20/rpmbuild/SPECS/golang.spec
@@ -115,7 +115,7 @@

 Name:           golang
 Version:        %{go_version}
-Release:        %{baserelease}%{?dist}
+Release:        %{?_buildid}%{?dist}.eks
 Summary:        The Go Programming Language
 # source tree includes several copies of Mark.Twain-Tom.Sawyer.txt under Public Domain
 License:        BSD and Public Domain
@@ -127,8 +127,6 @@ Source1:        fedora.go
 # The compiler is written in Go. Needs go(1.4+) compiler for build.
 %if !%{golang_bootstrap}
 BuildRequires:  gcc-go >= 5
-%else
-BuildRequires:  golang > 1.4
 %endif
 %if 0%{?rhel} > 6 || 0%{?fedora} > 0
 BuildRequires:  hostname
@@ -160,6 +158,7 @@ Requires:       %{name}-src = %{version}-%{release}
 Patch2:       0002-syscall-expose-IfInfomsg.X__ifi_pad-on-s390x.patch
 Patch3:       0003-cmd-go-disable-Google-s-proxy-and-sumdb.patch
 Patch4:       0004-cmd-link-use-gold-on-ARM-ARM64-only-if-gold-is-avail.patch
+Patch5:       0104-add-method-to-skip-privd-tests-if-required.patch

 # Having documentation separate was broken
 Obsoletes:      %{name}-docs < 1.1-4
@@ -287,7 +286,7 @@ Requires:       %{name} = %{version}-%{release}
 %endif

 %prep
-%autosetup -p1 -n go
+%autosetup -p1 -n go-go%{go_version}

 cp %{SOURCE1} ./src/runtime/

@@ -535,6 +534,9 @@ fi
 %endif

 %changelog
+* Mon Feb 06 2023 Kirsten Schumy <ksschumy@amazon.com> - 1.20-1
+- Added go1.20 to eks-distro-build-tooling
+
 * Thu Feb 02 2023 Alejandro Sáez <asm@redhat.com> - 1.20-1
 - Update to go1.20
 - Resolves: rhbz#2152070
````
----

### This is what I changed from the test skip patch from 1.19. Note the extra test being skipped.

````diff
diff --git a/projects/golang/go/1.19/patches/0104-add-method-to-skip-privd-tests-if-required.patch b/projects/golang/go/1.19/patches/0104-add-method-to-skip-privd-tests-if-required.patch
index aa13aa9..c9ec781 100644
--- a/projects/golang/go/1.19/patches/0104-add-method-to-skip-privd-tests-if-required.patch
+++ b/projects/golang/go/1.19/patches/0104-add-method-to-skip-privd-tests-if-required.patch
@@ -1,17 +1,17 @@
-From c1ac178bd9f0148b28f2b421030df77e6aff46a6 Mon Sep 17 00:00:00 2001
+From 7293851230d330152fde30d3263e94005795591f Mon Sep 17 00:00:00 2001
 From: Daniel Budris <budris@amazon.com>
 Date: Tue, 4 Oct 2022 16:31:07 -0400
 Subject: [PATCH] add method to skip privd tests if required

 ---
- src/syscall/exec_linux_test.go | 8 ++++++++
- 1 file changed, 8 insertions(+)
+ src/syscall/exec_linux_test.go | 9 +++++++++
+ 1 file changed, 9 insertions(+)

 diff --git a/src/syscall/exec_linux_test.go b/src/syscall/exec_linux_test.go
-index 181fb1e849..085ee7f7eb 100644
+index a6900f9033..09fc8322cf 100644
 --- a/src/syscall/exec_linux_test.go
 +++ b/src/syscall/exec_linux_test.go
-@@ -49,6 +49,12 @@ func skipInContainer(t *testing.T) {
+@@ -52,6 +52,12 @@ func skipInContainer(t *testing.T) {
        }
  }

@@ -24,7 +24,7 @@ index 181fb1e849..085ee7f7eb 100644
  func skipNoUserNamespaces(t *testing.T) {
        if _, err := os.Stat("/proc/self/ns/user"); err != nil {
                if os.IsNotExist(err) {
-@@ -343,6 +349,7 @@ func TestUnshareMountNameSpaceHelper(*testing.T) {
+@@ -327,6 +333,7 @@ func TestUnshareMountNameSpaceHelper(*testing.T) {
  // Test for Issue 38471: unshare fails because systemd has forced / to be shared
  func TestUnshareMountNameSpace(t *testing.T) {
        skipInContainer(t)
@@ -32,7 +32,7 @@ index 181fb1e849..085ee7f7eb 100644
        // Make sure we are running as root so we have permissions to use unshare
        // and create a network namespace.
        if os.Getuid() != 0 {
-@@ -385,6 +392,7 @@ func TestUnshareMountNameSpace(t *testing.T) {
+@@ -369,6 +376,7 @@ func TestUnshareMountNameSpace(t *testing.T) {
  // Test for Issue 20103: unshare fails when chroot is used
  func TestUnshareMountNameSpaceChroot(t *testing.T) {
        skipInContainer(t)
@@ -40,6 +40,14 @@ index 181fb1e849..085ee7f7eb 100644
        // Make sure we are running as root so we have permissions to use unshare
        // and create a network namespace.
        if os.Getuid() != 0 {
---
-2.30.1 (Apple Git-130)
+@@ -634,6 +642,7 @@ func TestAmbientCapsHelper(*testing.T) {
+ }
+
+ func TestAmbientCaps(t *testing.T) {
++      skipPrivilegedTests(t)
+       // Make sure we are running as root so we have permissions to use unshare
+       // and create a network namespace.
+       if os.Getuid() != 0 {
+--
+2.39.1
````

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by danbudris** [comment]
https://github.com/aws/eks-distro-build-tooling/issues/799

**Comment by danbudris** [comment]
we'll want to remove that `tar.tar` src from `SOURCES`

**Comment by kschumy** [comment]
> we'll want to remove that `tar.tar` src from `SOURCES`

@danbudris Do you mean to delete the file? I did that

**Pull request merged**
