### PR TITLE
Add tag update automation for eks-anywhere repos

### PR DESCRIPTION
**Pull request by abhay-krishna**
Add tag update automation to EKS Anywhere build tooling and Prowjob repos
/hold

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by abhay-krishna** [comment]
Tests will most likely fail

**Review by TerryHowe — APPROVED** [review]
/lgtm

**Comment by TerryHowe** [comment]
I assume the tests will pass when the other PR merges

**Comment by abhay-krishna** [comment]
> I assume the tests will pass when the other PR merges

Yes, and after I create the respective forks on the bot's account.

**Review by jaxesn — APPROVED** [review]
/lgtm

**Pull request merged**
