### PR TITLE
Bump buildkit version to v0.10.1 in builder-base

### PR DESCRIPTION
**Pull request by abhay-krishna**
Keeping buildkit version aligned with Prowjobs - refer to aws/eks-distro-prow-jobs#309

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by jaxesn — APPROVED** [review]
/approve

**Comment by abhay-krishna** [comment]
Just rebased

/unhold

**Comment by abhay-krishna** [comment]
Just rebased

/unhold

**Review by jaxesn — APPROVED** [review]
/approve

**Pull request merged**
